using System.Net.Http;
using System.Web;
using System.Web.Security;
using WebMatrix.WebData;

namespace TS.FormsToTokenAccessAuthentication
{
    /// <summary>
    /// An implementation of the <see cref="ITokenGenerator"/> interface that uses 
    /// ASP.NET Forms Authentication to generate an authentication token.
    /// </summary>
    public sealed class FormsTokenGenerator
        : ITokenGenerator
    {
        AuthenticationToken ITokenGenerator.Login(HttpRequestMessage request, string userName, string password)
        {
            if (!WebSecurity.Login(userName, password))
                return null;

            // extract token from the cookie generated by the Forms Authentication login
            var httpContext = (HttpContextWrapper) request.Properties["MS_HttpContext"];
            var cookie = httpContext.Response.Cookies[FormsAuthentication.FormsCookieName];
            httpContext.Response.Cookies.Remove(FormsAuthentication.FormsCookieName);

            return new AuthenticationToken
                {
                    Value = cookie.Value,
                    Coverage = Constants.CoverageNoneName
                };
        }
    }
}