using System;
using System.Net.Http;
using System.Web;
using System.Web.Security;

namespace TS.FormsToTokenAccessAuthentication
{
    /// <summary>
    /// An implementation of the <see cref="ITokenGenerator"/> interface that uses 
    /// ASP.NET Forms Authentication to generate an authentication token.
    /// </summary>
    public sealed class FormsTokenGenerator
        : ITokenGenerator
    {
        private readonly IWebSecurityWrapper _webSecurity;

        /// <summary>
        /// Initializes a new instance of the <see cref="FormsTokenGenerator"/> with dependencies.
        /// </summary>
        public FormsTokenGenerator(IWebSecurityWrapper webSecurity)
        {
            if (webSecurity == null) throw new ArgumentNullException("webSecurity");
            _webSecurity = webSecurity;
        }

        AuthenticationToken ITokenGenerator.Login(HttpRequestMessage request, string userName, string password)
        {
            if (request == null) throw new ArgumentNullException("request");
            if (userName == null) throw new ArgumentNullException("userName");
            if (password == null) throw new ArgumentNullException("password");

            if (!_webSecurity.Login(userName, password))
                return null;

            // extract token from the cookie generated by the Forms Authentication login
            var httpContext = (HttpContextBase) request.Properties["MS_HttpContext"];
            var cookie = httpContext.Response.Cookies[FormsAuthentication.FormsCookieName];

            if (cookie == null)
                throw new InvalidOperationException("The membership provider did not set the Forms Authentication cookie.");

            httpContext.Response.Cookies.Remove(FormsAuthentication.FormsCookieName);

            return new AuthenticationToken
                {
                    Value = cookie.Value,
                    Coverage = Constants.CoverageNoneName
                };
        }
    }
}