using System;
using System.Web;

namespace TS.FormsToTokenAccessAuthentication
{
    /// <summary>
    /// An <see cref="IHttpModule"/> that handles incoming HTTP requests containing authentication tokens
    /// that conform to the Token Access Authentication spec 
    /// (http://tools.ietf.org/html/draft-hammer-http-token-auth-01) and converts them 
    /// to HTTP cookies that will get picked up by ASP.NET Forms Authentication.
    /// </summary>
    /// <remarks>
    /// For simplicity of implementation, this HTTP module extracts the token in the 
    /// HTTP Authorization header and creates an HTTP cookie, which then gets picked up by 
    /// the ASP.NET Forms Authentication system to perform the actual authentication.   
    /// Therefore the token must have been generated by Forms Authentication in the first place.
    /// </remarks>
    public sealed class FormsCookieGeneratorRequestModule
        : IHttpModule
    {
        void IHttpModule.Init(HttpApplication context)
        {
            context.BeginRequest += OnBeginRequest;
        }

        private static void OnBeginRequest(object sender, EventArgs eventArgs)
        {
            var httpContext = ((HttpApplication) sender).Context;
            var wrapper = new HttpContextWrapper(httpContext);

            IFormsCookieGenerator cookieGenerator = new FormsCookieGenerator();
            cookieGenerator.Generate(wrapper.Request);
        }

        void IHttpModule.Dispose()
        {
            // nothing to dispose
        }
    }
}