using System;
using System.Linq;
using System.Text.RegularExpressions;
using System.Web;
using System.Web.Security;

namespace TS.FormsToTokenAccessAuthentication
{
    /// <summary>
    /// An <see cref="IHttpModule"/> that handles incoming HTTP requests containing authentication tokens
    /// that conform to the Token Access Authentication spec 
    /// (http://tools.ietf.org/html/draft-hammer-http-token-auth-01) and converts them 
    /// to HTTP cookies that will get picked up by ASP.NET Forms Authentication.
    /// </summary>
    /// <remarks>
    /// For simplicity of implementation, this HTTP module extracts the token in the 
    /// HTTP Authorization header and creates an HTTP cookie, which then gets picked up by 
    /// the ASP.NET Forms Authentication system to perform the actual authentication.   
    /// Therefore the token must have been generated by Forms Authentication in the first place.
    /// </remarks>
    public sealed class FormsCookieGeneratorRequestModule
        : IHttpModule
    {
        void IHttpModule.Init(HttpApplication context)
        {
            context.BeginRequest += OnBeginRequest;
        }

        private static void OnBeginRequest(object sender, EventArgs eventArgs)
        {
            var httpContext = ((HttpApplication) sender).Context;

            // exit if request doesn't contain the auth header
            if (httpContext.Request.Headers.AllKeys.All(k => k != Constants.AuthorizationHeaderName))
                return;

            var authValue = httpContext.Request.Headers.Get(Constants.AuthorizationHeaderName);

            // detect scheme
            const string schemeName = "scheme";
            const string parameterName = "parameter";
            var schemePattern = string.Format(
                "^(?<{0}>\\S+)\\s+(?<{1}>.*)",
                schemeName, 
                parameterName);
            var schemeMatchs = Regex.Matches(authValue, schemePattern);
            if (schemeMatchs.Count == 1)
            {
                var schemeMatch = schemeMatchs[0];
                var scheme = schemeMatch.Groups[schemeName].Value;
                if (scheme == Constants.TokenSchemeName)
                {
                    var tokenAuthParameter = schemeMatch.Groups[parameterName].Value;

                    var tokenAuthPattern = string.Format(
                        "{0}=\"(?<{0}>.*)\",\\s*{1}=\"(?<{1}>.*)\"",
                        Constants.TokenAttributeName,
                        Constants.CoverageAttributeName);
                    var tokenAuthMatches = Regex.Matches(authValue, tokenAuthPattern);
                    if (tokenAuthMatches.Count == 1)
                    {
                        var tokenAuthMatch = tokenAuthMatches[0];
                        var coverage = tokenAuthMatch.Groups[Constants.CoverageAttributeName].Value;
                        if (coverage == Constants.CoverageNoneName)
                        {
                            var token = tokenAuthMatch.Groups[Constants.TokenAttributeName].Value;
                            if (!string.IsNullOrWhiteSpace(token))
                            {
                                var cookie = new HttpCookie(FormsAuthentication.FormsCookieName, token);
                                httpContext.Request.Cookies.Add(cookie);
                            }
                            else
                                WriteError(httpContext, "Token is empty");
                        }
                        else
                            WriteError(httpContext, "Unsupported coverage name: " + coverage);
                    }
                    else
                        WriteError(httpContext,
                                   "Unsupported token authentication parameter value: " + tokenAuthParameter);
                }
                else
                    WriteError(httpContext, "Unsupported authentication scheme: " + scheme);
            }
            else
            {
                if (authValue == Constants.TokenSchemeName)
                    WriteError(httpContext, "Missing token parameter value");
                else
                    WriteError(httpContext, "Unsupported authentication method: " + authValue);
            }
        }

        private static void WriteError(HttpContext httpContext, string message)
        {
            // write error message to throw-away request header so it can be picked up by message handler later in pipeline
            httpContext.Request.Headers.Add(Constants.ErrorMessageTempHeaderName, message);
        }

        void IHttpModule.Dispose()
        {
            // nothing to dispose
        }
    }
}